title: Automate tasks with cron
hero_image: images/banner.png
description: Use cron to automate tasks
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "bash, nix"
steps:
  - title: Automate tasks with cron
